- name: Restart MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted

- name: Restart Memcached
  ansible.builtin.systemd:
    name: memcached
    state: restarted


- name: Restart rabbitmq
  systemd:
    name: rabbitmq-server
    state: restarted