- name: Install MongoDB
  import_tasks: mongo_install.yml
  tags: mongo

- name: Install Memcached
  import_tasks: memcached_install.yml
  tags: memcached

- name: Install RabbitMQ
  import_tasks: rabbitmq_install.yml
  tags: rabbitmq