- name: Install Memcached package
  ansible.builtin.apt:
    name: memcached
    state: present
    update_cache: yes

- name: Configure Memcached memory allocation
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    regexp: '^-m\s+'
    line: '-m 256'
    backup: yes
  notify: Restart Memcached

- name: Remove all other -l directives
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    regexp: '^-l\s+'
    state: absent
    backup: yes

- name: Add desired -l directive
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    line: '-l 0.0.0.0'
    create: yes
    insertafter: EOF
  notify: Restart Memcached

- name: Ensure Memcached is enabled and running
  ansible.builtin.systemd:
    name: memcached
    enabled: yes
    state: started

- name: Wait for Memcached to be ready
  ansible.builtin.wait_for:
    port: 11211
    delay: 2
    timeout: 10

- name: Test Memcached connectivity
  ansible.builtin.shell: echo "version" | nc localhost 11211
  register: memcached_test
  changed_when: false
  failed_when: memcached_test.rc != 0
