- name: tomcat installing 
  import_tasks: tomcat_install.yml

- name: configuring tomcat user, host-manager and manager 
  import_tasks: tomcat_config.yml

- name: installing nexus
  import_tasks: nexus_install.yml


- name: installing sonar
  import_tasks: sonar_install.yml
