
- name: Install required packages for extracting archives
  apt:
    name:
      - tar
      - gzip
      - bzip2
      - xz-utils
      - unzip
    state: present
    update_cache: yes


- name: Create nexus user
  user:
    name: "{{ nexus_user }}"
    shell: /bin/bash
    home: /opt/nexus
    system: yes


- name: Download Nexus
  get_url:
    url:  "{{ nexus_download_url }}"
    dest: "{{ nexus_archive_path }}"
    mode: '0644'

- name: Extract Nexus
  unarchive:
    src:  "{{ nexus_archive_path }}"
    dest: "{{ nexus_extract_dir }}"
    remote_src: yes



- name: Check if {{ nexus_symlink_path }} exists
  stat:
    path: "{{ nexus_symlink_path }}"
  register: nexus_should_remove_dir
  become: true

- name: Remove existing "{{ nexus_symlink_path }}" directory if it is not a symlink
  file:
    path: /opt/nexus
    state: absent
  when: nexus_should_remove_dir.stat.exists and not nexus_should_remove_dir.stat.islnk
  become: true


- name: Create symlink for nexus
  file:
    src:  "{{ nexus_extracted_path }}"
    dest: "{{ nexus_symlink_path }}"
    state: link


- name: Change ownership of Nexus directories
  file:
    path: "{{ nexus_extracted_path }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    state: directory
    recurse: yes
- name: Ensure nexus script is executable
  file:
    path: "{{ nexus_symlink_path }}/bin/nexus"
    mode: '0755'
    state: file


- name: Set run_as_user to nexus in nexus.rc
  lineinfile:
    path: "{{ nexus_symlink_path }}/bin/nexus.rc"
    line: 'run_as_user="{{ nexus_user }}"'
    create: yes


- name: Create systemd service for Nexus
  copy:
    dest: /etc/systemd/system/nexus.service
    content: |
      [Unit]
      Description=nexus service
      After=network.target
      [Service]
      Type=forking
      LimitNOFILE=65536
      ExecStart=/bin/bash {{ nexus_symlink_path }}/bin/nexus start
      ExecStop=/bin/bash {{ nexus_symlink_path }}/bin/nexus stop
      User={{ nexus_user }}
      Restart=on-abort
      [Install]
      WantedBy=multi-user.target


- name: Ensure nexus work directory exists and owned by nexus user
  file:
    path: "{{ nexus_work_dir }}"
    state: directory
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    mode: '0755'
    recurse: yes
  become: true


- name: Reload systemd
  command: systemctl daemon-reexec
- name: Enable and start Nexus service
  systemd:
    name: nexus
    enabled: yes
    state: started