handlers:
  - name: Reload systemd
    command: systemctl daemon-reexec
    become: true

  - name: Start Tomcat
    systemd:
      name: tomcat
      state: started
      enabled: yes
    become: true
